# This config is used when the docker compose file starts the prometheus container.

# Scrape configuration containing endpoints to scrape (multiple are possible):
scrape_configs:
  - job_name: 'quarkus-blog-api'
    metrics_path: '/q/metrics'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8080']
