# Global prometheus config. This config is used when the docker compose file starts the prometheus container.
global:
 scrape_interval:     3s
 evaluation_interval: 10s
 scrape_timeout:      10s

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

# Scrape configuration containing endpoints to scrape (multiple are possible):
 - job_name: 'quarkus-blog-api'
   metrics_path: '/q/metrics'
   scrape_interval: 3s
   static_configs:
     - targets: ['host.docker.internal:8080']