name: blog rest service native CI build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PROJECT_NAME: blog-rest-service
  PROJECT_VERSION: latest

jobs:
  build-and-push-native-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-repo
        uses: actions/checkout@v3

      - name: Download and install GraalVM
        run: |
          GRAALVM_VERSION=21.3.3  # Replace with the desired GraalVM version
          GRAALVM_HOME=$HOME/graalvm-ce-java17-$GRAALVM_VERSION
          wget https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-$GRAALVM_VERSION/graalvm-ce-java17-linux-amd64-$GRAALVM_VERSION.tar.gz
          tar -xzf graalvm-ce-java17-linux-amd64-$GRAALVM_VERSION.tar.gz -C $HOME
          echo "GRAALVM_HOME=$GRAALVM_HOME" >> $GITHUB_ENV
          echo "$GRAALVM_HOME/bin" >> $GITHUB_PATH

      - name: Install native-image tool
        run: |
          source $GITHUB_ENV
          gu install native-image

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Quarkus native image
        run: mvn clean package -Pnative --define quarkus.native.container-build=true -B

      - name: Build Docker image for native binary
        run: docker build -f src/main/docker/Dockerfile.native -t ${{ env.REGISTRY }}/getwombats/${{ env.PROJECT_NAME }}-native:${{ env.PROJECT_VERSION }} .

      - name: Push Docker image to GitHub Container Registry
        run: docker push ${{ env.REGISTRY }}/getwombats/${{ env.PROJECT_NAME }}-native:${{ env.PROJECT_VERSION }}
